## What is an API?
An API is a set of rules and protocols that allow different software applications to communicate with each other. APIs define the methods and data formats that applications can use to request and exchange information, enabling developers to leverage existing services and data sources instead of building everything from scratch.

## Types of APIs
There are several types of APIs, including:

REST (Representational State Transfer): A popular architectural style for designing networked applications. RESTful APIs use standard HTTP methods (GET, POST, PUT, DELETE) and are typically used for web services.
SOAP (Simple Object Access Protocol): An older protocol for exchanging structured information in web services. SOAP uses XML for message formatting and relies on a set of rules for message structure.
GraphQL: A query language for APIs developed by Facebook, allowing clients to request exactly the data they need, making it more efficient than REST in some scenarios.

## How to Fetch Data from an API
Fetching data from an API typically involves making an HTTP request to a specific endpoint and processing the response. Here’s a step-by-step guide to fetching data from a RESTful API using Python.

## Step 1: Understand the API Documentation
Before you start coding, it’s essential to understand the API you’re working with. Most APIs provide documentation that explains the available endpoints, request parameters, authentication methods, and response formats. Take the time to read through the documentation to familiarize yourself with the API.### 

Step 2: Set Up Your Development Environment
To fetch data from an API, you’ll need a development environment with Python installed. You’ll also need a library to make HTTP requests. In this example, we’ll use the requests library, which is popular for its simplicity and ease of use.

Install Python: If you don’t have Python installed, download and install it from python.org.
Install the requests Library: You can install the requests library using pip.
pip install r### equests
Step 3: Write the Code
Create a new Python file, e.g., fetch_data.py, and add the following code:

import requests
response = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=256da2d742d5a5979790e6833447e4b4').json()
Popularity = []
Vote_count = []
Orignal_lang = []
Title = []
Vote_avg = []
Overview = []
Release_Data = []

for i in response['results']:
    Popularity.append(i['popularity'])
    Vote_count.append(i['vote_count'])
    Orignal_lang.append(i['original_language'])
    Title.append(i['title'])
    Vote_avg.append(i['vote_average'])
    Overview.append(i['overview'])
    Release_Data.append(i['release_date'])

d = {'title':Title,'Overview':Overview,'Orignal_lang':Orignal_lang,'Release_Data':R

### Explanation
This code snippet does the following:

Imports the requests Library: We use the requests library to make HTTP requests.
Defines the API Endpoint: We specify the URL of the API endpoint we want to fetch data from.
Creates Variables to Store Data: We initialize empty lists to store the data we fetch from the API response.
Processes the Response: We loop through the results in the API response and append the relevant data to our lists.
Creates a Dictionary to Organize Data: We combine our lists into a dictionary for easier acc ss and manipu

 ation.
Best Practices for Fetching Data from APIs
Handle Errors Gracefully: Always include error handling to manage network issues, invalid responses, or other unexpected conditions.
Use Environment Variables: Store sensitive information, such as API keys and secrets, in environment variables to keep them secure.
Respect Rate Limits: Many APIs impose rate limits to prevent abuse. Be mindful of these limits and implement appropriate throttling in your code.
Cache Responses: To improve performance and reduce the number of requests, consider caching API responses when appropriate.
Use Pagination: When dealing with large datasets, use pagination to fetch data in smaller chunks, rather than retrieving everything in a single request.
Keep Your Code Modular: Organize your code into reusable modules to make it easier to maintain and extend.

In [2]:
import requests
response = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=256da2d742d5a5979790e6833447e4b4').json()
#importing and defining API endpoint
Popularity = []
Vote_count = []
Orignal_lang = []#storing the data from API response
Title = []
Vote_avg = []
Overview = []
Release_Data = []

In [4]:
for i in response['results']:#loop through the results in API response and append data to list then convert into dictionary
    Popularity.append(i['popularity'])
    Vote_count.append(i['vote_count'])
    Orignal_lang.append(i['original_language'])
    Title.append(i['title'])
    Vote_avg.append(i['vote_average'])
    Overview.append(i['overview'])
    Release_Data.append(i['release_date'])

d = {'title':Title,'Overview':Overview,'Orignal_lang':Orignal_lang,'Release_Data':Release_Data,'Popularity':Popularity,'Vote_count':Vote_count,'Vote_avg':Vote_avg}

In [5]:
d

{'title': ['A Working Man',
  'A Minecraft Movie',
  'In the Lost Lands',
  'Bullet Train Explosion',
  'The Siege',
  'Havoc',
  'Sinners',
  'Captain America: Brave New World',
  'G20',
  'Novocaine',
  'Conclave',
  'Ash',
  'Gunslingers',
  'The Woman in the Yard',
  'Locked',
  'Moana 2',
  'Sonic the Hedgehog 3',
  'Mufasa: The Lion King',
  'Laila',
  'Avengers: Infinity War',
  'A Working Man',
  'A Minecraft Movie',
  'In the Lost Lands',
  'Bullet Train Explosion',
  'The Siege',
  'Havoc',
  'Sinners',
  'Captain America: Brave New World',
  'G20',
  'Novocaine',
  'Conclave',
  'Ash',
  'Gunslingers',
  'The Woman in the Yard',
  'Locked',
  'Moana 2',
  'Sonic the Hedgehog 3',
  'Mufasa: The Lion King',
  'Laila',
  'Avengers: Infinity War'],
 'Overview': ["Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
  "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
  'A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.',
  'When panic erupts on a Tokyo-bound bullet train that will explode if it slows below 100 kph, authorities race against time to save everyone on board.',
  'International assassin Walker is compromised during a mission and sent to a reassignment center for a new identity. During his stay at the facility, a ruthless assault team storms the compound searching for someone their boss has lost. Walker begrudgingly falls in with skilled hitwoman Elda and her mysterious ward Juliet in order to survive the night.',
  "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
  'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
  'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
  'After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.',
  'When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.',
  'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
  'A woman wakes up on a distant planet and finds the crew of her space station viciously killed. Her investigation into what happened sets in motion a terrifying chain of events.',
  'When the most wanted man in America surfaces in a small Kentucky town, his violent history -- and a blood-thirsty mob seeking vengeance and a king’s ransom -- soon follow. As brothers face off against one another and bullets tear the town to shreds, this lightning-fast gunslinger makes his enemies pay the ultimate price for their greed.',
  "In the aftermath of her husband's death, widow Ramona's struggle to raise her two kids is hindered by the arrival of a mysterious woman with supernatural abilities.",
  'When Eddie breaks into a luxury SUV, he steps into a deadly trap set by William, a self-proclaimed vigilante delivering his own brand of twisted justice. With no means of escape, Eddie must fight to survive in a ride where escape is an illusion, survival is a nightmare, and justice shifts into high gear.',
  "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
  'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
  'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
  'Sonu Model, a renowned beautician from the old city, is forced to disguise himself as Laila, leading to a series of comedic, romantic, and action-packed events. Chaos ensues in this hilarious laugh riot',
  'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
  "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
  "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
  'A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.',
  'When panic erupts on a Tokyo-bound bullet train that will explode if it slows below 100 kph, authorities race against time to save everyone on board.',
  'International assassin Walker is compromised during a mission and sent to a reassignment center for a new identity. During his stay at the facility, a ruthless assault team storms the compound searching for someone their boss has lost. Walker begrudgingly falls in with skilled hitwoman Elda and her mysterious ward Juliet in order to survive the night.',
  "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
  'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
  'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
  'After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.',
  'When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.',
  'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
  'A woman wakes up on a distant planet and finds the crew of her space station viciously killed. Her investigation into what happened sets in motion a terrifying chain of events.',
  'When the most wanted man in America surfaces in a small Kentucky town, his violent history -- and a blood-thirsty mob seeking vengeance and a king’s ransom -- soon follow. As brothers face off against one another and bullets tear the town to shreds, this lightning-fast gunslinger makes his enemies pay the ultimate price for their greed.',
  "In the aftermath of her husband's death, widow Ramona's struggle to raise her two kids is hindered by the arrival of a mysterious woman with supernatural abilities.",
  'When Eddie breaks into a luxury SUV, he steps into a deadly trap set by William, a self-proclaimed vigilante delivering his own brand of twisted justice. With no means of escape, Eddie must fight to survive in a ride where escape is an illusion, survival is a nightmare, and justice shifts into high gear.',
  "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
  'Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.',
  'Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.',
  'Sonu Model, a renowned beautician from the old city, is forced to disguise himself as Laila, leading to a series of comedic, romantic, and action-packed events. Chaos ensues in this hilarious laugh riot',
  'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.'],
 'Orignal_lang': ['en',
  'en',
  'en',
  'ja',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'te',
  'en',
  'en',
  'en',
  'en',
  'ja',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'en',
  'te',
  'en'],
 'Release_Data': ['2025-03-26',
  '2025-03-31',
  '2025-02-27',
  '2025-04-23',
  '2023-03-10',
  '2025-04-24',
  '2025-04-16',
  '2025-02-12',
  '2025-04-09',
  '2025-03-12',
  '2024-10-25',
  '2025-03-20',
  '2025-04-11',
  '2025-03-27',
  '2025-03-20',
  '2024-11-21',
  '2024-12-19',
  '2024-12-18',
  '2025-02-14',
  '2018-04-25',
  '2025-03-26',
  '2025-03-31',
  '2025-02-27',
  '2025-04-23',
  '2023-03-10',
  '2025-04-24',
  '2025-04-16',
  '2025-02-12',
  '2025-04-09',
  '2025-03-12',
  '2024-10-25',
  '2025-03-20',
  '2025-04-11',
  '2025-03-27',
  '2025-03-20',
  '2024-11-21',
  '2024-12-19',
  '2024-12-18',
  '2025-02-14',
  '2018-04-25'],
 'Popularity': [740.0953,
  476.026,
  364.108,
  352.3333,
  287.6579,
  497.0919,
  248.4648,
  262.1664,
  203.212,
  198.2433,
  210.6966,
  205.1028,
  160.8356,
  157.7558,
  158.4168,
  142.7992,
  135.9041,
  136.4473,
  135.1795,
  130.5899,
  740.0953,
  476.026,
  364.108,
  352.3333,
  287.6579,
  497.0919,
  248.4648,
  262.1664,
  203.212,
  198.2433,
  210.6966,
  205.1028,
  160.8356,
  157.7558,
  158.4168,
  142.7992,
  135.9041,
  136.4473,
  135.1795,
  130.5899],
 'Vote_count': [436,
  728,
  288,
  55,
  39,
  136,
  382,
  1624,
  379,
  611,
  2078,
  86,
  40,
  97,
  77,
  2284,
  2469,
  2019,
  3,
  30450,
  436,
  728,
  288,
  55,
  39,
  136,
  382,
  1624,
  379,
  611,
  2078,
  86,
  40,
  97,
  77,
  2284,
  2469,
  2019,
  3,
  30450],
 'Vote_avg': [6.297,
  6.2,
  6.292,
  6.4,
  5.333,
  6.68,
  7.573,
  6.143,
  6.629,
  6.9,
  7.198,
  5.674,
  6.775,
  6.0,
  6.104,
  7.081,
  7.727,
  7.414,
  5.0,
  8.235,
  6.297,
  6.2,
  6.292,
  6.4,
  5.333,
  6.68,
  7.573,
  6.143,
  6.629,
  6.9,
  7.198,
  5.674,
  6.775,
  6.0,
  6.104,
  7.081,
  7.727,
  7.414,
  5.0,
  8.235]}

In [7]:
import pandas as pd
df=pd.DataFrame(d)

In [8]:
df.head()

                    title                                           Overview  ... Vote_count Vote_avg
0           A Working Man  Levon Cade left behind a decorated military ca...  ...        436    6.297
1       A Minecraft Movie  Four misfits find themselves struggling with o...  ...        728    6.200
2       In the Lost Lands  A queen sends the powerful and feared sorceres...  ...        288    6.292
3  Bullet Train Explosion  When panic erupts on a Tokyo-bound bullet trai...  ...         55    6.400
4               The Siege  International assassin Walker is compromised d...  ...         39    5.333

[5 rows x 7 columns]

In [9]:
df.describe()

       Popularity   Vote_count   Vote_avg
count   40.000000     40.00000  40.000000
mean   260.156325   2214.05000   6.582750
std    155.819678   6613.97078   0.800252
min    130.589900      3.00000   5.000000
25%    154.016650     83.75000   6.133250
50%    204.157400    380.50000   6.514500
75%    303.826750   1722.75000   7.110250
max    740.095300  30450.00000   8.235000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         40 non-null     object
 1   Overview      40 non-null     object
 2   Orignal_lang  40 non-null     object
 3   Release_Data  40 non-null     object
 4   Popularity    40 non-null     float64
 5   Vote_count    40 non-null     int64
 6   Vote_avg      40 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.3+ KB

In [11]:
df.to_csv('Imdb_Movies_dataset.csv')

In [12]:
#Example 2
import json

In this Python program fetches the live stock data for "IBM" from the Alpha Vantage API using the 5-minute interval and prints the opening price.Here we make use of 'requests' to make a call and it is checked with the help of status code that whether our request was successful or not.Then the response is converted to python dictionary and the respected data is stored .

In [20]:
def get_stock():
    '''This function fetches the API data from stockmarket to an csv file
    '''
    url="https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&outputsize=full&apikey=demo"
    res=requests.get(url)
    if res.status_code==200:
        data=res.json()
        last_refreshed=data["Meta Data"]["3. Last Refreshed"]
        price=data['Time Series (5min)'][last_refreshed]['1. open']
        return price
    else:
        return None

stock_price={}
price=get_stock()
symbol="IBM"
if price is not None:
    stock_price[symbol]=price
print(symbol,price)

IBM 232.5500

In [21]:
import requests

# Replace 'API_KEY' with your actual API key from NewsAPI
API_KEY = '3805f6bbabcb42b3a0c08a489baf603d'
url = f"https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey={API_KEY}"
response = requests.get(url)
print(response.status_code)

200

In [22]:
import json
import requests

def fetch_and_print_articles(api_url):
    response = requests.get(api_url)
    
    if response.status_code == 200:
        articles = response.json().get('articles', [])
        
        for index, article in enumerate(articles[:3], start=1):
            print(f"Article {index}:\n{json.dumps(article, sort_keys=True, indent=4)}\n")
    else:
        print(f"Error: {response.status_code}")

API_KEY = '3805f6bbabcb42b3a0c08a489baf603d'
api_endpoint = f"https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey={API_KEY}"

fetch_and_print_articles(api_endpoint)

def jprint(obj):
    print(json.dumps(obj, sort_keys=True, indent=4))

# Example usage:
# jprint(response.json())

Article 1:
{
    "author": "Financial Times",
    "content": null,
    "description": null,
    "publishedAt": "2025-04-26T02:01:01Z",
    "source": {
        "id": null,
        "name": "Financial Times"
    },
    "title": "Boeing\u2019s return flight highlights America Inc\u2019s exposure to China - Financial Times",
    "url": "https://www.ft.com/content/6df594e8-92c7-4e11-a796-43e67dc7debc",
    "urlToImage": null
}

Article 2:
{
    "author": "Emily Wunderlich",
    "content": "St. Petersburg-Clearwater International Airport was closed for several hours Friday afternoon while law enforcement officials investigated a bomb threat, according to Pinellas County Sheriff Bob Gual\u2026 [+1038 chars]",
    "description": "An Allegiant plane was evacuated after a flight attendant found a threat on a bathroom door, according to Pinellas County Sheriff Bob Gualtieri.",
    "publishedAt": "2025-04-25T23:15:03Z",
    "source": {
        "id": null,
        "name": "Tampa Bay Times"
    },
    "title": "Bomb threat prompts closure of St. Pete-Clearwater airport, sheriff says - Tampa Bay Times",
    "url": "https://www.tampabay.com/news/breaking-news/2025/04/25/st-petersburg-clearwater-international-airport-closed-today/",
    "urlToImage": "https://www.tampabay.com/resizer/v2/23UNBDMOC5BW5EBVMYSJ3MSVHY.png?auth=77d4ac8406c2e24135ded55cf6214c232c53983e54fe53c28c5bb2fe7a7d6f2a&height=675&width=1200&smart=true"
}

Article 3:
{
    "author": "Kirsten Korosec",
    "content": "Welcome back to TechCrunch Mobility your central hub for news and insights on the future of transportation. Sign up here for free just click TechCrunch Mobility!\r\nBusy week, so lets get to it. Starti\u2026 [+7152 chars]",
    "description": "Welcome back to TechCrunch Mobility \u2014 your central hub for news and insights on the future of transportation. Sign up here for free \u2014 just click",
    "publishedAt": "2025-04-25T22:30:00Z",
    "source": {
        "id": "techcrunch",
        "name": "TechCrunch"
    },
    "title": "TechCrunch Mobility: Slate\u2019s \u2018transformer\u2019 EV truck breaks cover and Tesla\u2019s dueling realities - TechCrunch",
    "url": "https://techcrunch.com/2025/04/25/techcrunch-mobility-slates-transformer-ev-truck-breaks-cover-and-teslas-dueling-realities/",
    "urlToImage": "https://techcrunch.com/wp-content/uploads/2025/04/Inspo_Truck_web.jpg?resize=1200,800"
}

In [23]:
import requests

# API endpoint and key
API_URL = "https://newsapi.org/v2/top-headlines"
API_KEY = "3805f6bbabcb42b3a0c08a489baf603d"

# Parameters for the API request
params = {
    "country": "us",
    "apiKey": API_KEY
}

# Making the API request
response = requests.get(API_URL, params=params)

# Checking if the request was successful
if response.status_code == 200:
    # Printing the JSON response
    print(response.json())
else:
    print(f"Error: {response.status_code}")

{'status': 'ok', 'totalResults': 35, 'articles': [{'source': {'id': 'the-wall-street-journal', 'name': 'The Wall Street Journal'}, 'author': 'WSJ', 'title': 'The Chinese Satellite Firm Washington Accuses of Helping U.S. Foes - WSJ', 'description': None, 'url': 'https://www.wsj.com/world/china/the-chinese-satellite-firm-washington-accuses-of-helping-u-s-foes-b5e68d2e', 'urlToImage': None, 'publishedAt': '2025-04-26T03:00:00Z', 'content': None}, {'source': {'id': None, 'name': 'Steelers.com'}, 'author': None, 'title': 'How he fits: Kaleb Johnson, RB, Iowa - Steelers.com', 'description': 'Steelers add big, explosive running back to offense', 'url': 'https://www.steelers.com/news/steelers-how-he-fits-kaleb-johnson-rb-iowa', 'urlToImage': 'https://static.clubs.nfl.com/image/upload/t_editorial_landscape_12_desktop/steelers/sitxpggfyp3by8xaqmx4', 'publishedAt': '2025-04-26T02:52:26Z', 'content': None}, {'source': {'id': None, 'name': 'clevelandbrowns.com'}, 'author': None, 'title': 'Browns select RB Quinshon Judkins with the No. 36 pick in the 2025 NFL Draft - Cleveland Browns', 'description': 'Judkins totaled 94 carries for 1,060 rushing yards and 14 touchdowns in 2024 season at OSU', 'url': 'https://www.clevelandbrowns.com/news/browns-select-rb-quinshon-judkins-with-the-no-36-pick-in-the-2025-nfl-draft', 'urlToImage': 'https://static.clubs.nfl.com/image/upload/t_editorial_landscape_12_desktop/browns/jlh8qymtql0coqwctkwf', 'publishedAt': '2025-04-26T02:16:44Z', 'content': None}, {'source': {'id': 'fox-sports', 'name': 'Fox Sports'}, 'author': 'Rob Rang', 'title': '2025 NFL Draft: Shedeur Sanders among best players available on Day 2 - FOX Sports', 'description': "The Shedeur Sanders slide that had been rumored for days has manifested beyond belief. He's now among Rob Rang's best players available heading into Day 3 of the NFL Draft.", 'url': 'https://www.foxsports.com/stories/nfl/2025-nfl-draft-best-players-available', 'urlToImage': 'https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2025/04/1408/814/16x9-2.jpg?ve=1&tl=1', 'publishedAt': '2025-04-26T02:14:00Z', 'content': 'A Shedeur Sanders slide had been rumored for days, but no one knew for certain when the polarizing quarterback would be selected. After Day 2 of the 2025 NFL Draft, that still remains a mystery.\r\nThr… [+15162 chars]'}, {'source': {'id': 'the-washington-post', 'name': 'The Washington Post'}, 'author': 'Mark Berman', 'title': 'Former congressman George Santos sentenced to more than 7 years in prison - The Washington Post', 'description': 'Former U.S. representative George Santos pleaded guilty last year to federal charges of aggravated identity theft and wire fraud.', 'url': 'https://www.washingtonpost.com/politics/2025/04/25/george-santos-sentencing-fraud-case/', 'urlToImage': 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/DTFL4R5PIM2EYHJMM5A3SP7ATU_size-normalized.jpg&w=1440', 'publishedAt': '2025-04-26T01:57:47Z', 'content': 'George Santos, the disgraced former congressman who was expelled from the House after being accused of financial misconduct and telling myriad lies about his background, was sentenced Friday to more … [+5086 chars]'}, {'source': {'id': None, 'name': 'BBC News'}, 'author': None, 'title': 'Virginia Giuffre, Prince Andrew and Jeffrey Epstein accuser, dies by suicide - BBC', 'description': 'Giuffre alleged she was trafficked to the Duke of York when she was 17, which he has strenuously denied.', 'url': 'https://www.bbc.com/news/articles/cql67qk0dd3o', 'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/faf7/live/905212e0-223e-11f0-83ed-3374ea04608c.jpg', 'publishedAt': '2025-04-26T01:48:32Z', 'content': 'Christal Hayes\r\nVirginia Giuffre, who accused Prince Andrew and Jeffrey Epstein of sexual abuse, has died by suicide aged 41, her family has confirmed.\r\nGiuffre was one of the most outspoken accusers… [+2885 chars]'}, {'source': {'id': None, 'name': 'Mile High Report'}, 'author': 'Tim Lynch', 'title': 'Snap reactions to the Broncos second round pick, RJ Harvey - Mile High Report', 'description': 'The Denver Broncos maneuvered through the back half of the second round in brilliant fashion and still landed their home run threat at running back.', 'url': 'https://www.milehighreport.com/2025/4/25/24417230/reactions-to-denver-broncos-second-round-pick-of-rj-harvey', 'urlToImage': 'https://cdn.vox-cdn.com/thumbor/xuKuX6HYK8Fht2E_g0dUtuOV0Z8=/0x0:4800x2513/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/25970011/usa_today_24656312.jpg', 'publishedAt': '2025-04-26T01:31:53Z', 'content': 'The Denver Broncos made some excellent moves to trade back twice from the 51st pick to the 60th moving up double-digit spots in both the third and fourth round, while also picking up an additional fo… [+2321 chars]'}, {'source': {'id': None, 'name': 'NPR'}, 'author': '', 'title': 'Justice Department revokes Biden-era protections for reporters in leak investigations - NPR', 'description': 'In a new memo, Attorney General Pam Bondi said the DOJ will allow for subpoenas, court orders and search warrants to get information and testimony from journalists.', 'url': 'https://www.npr.org/2025/04/25/nx-s1-5377624/pam-bondi-reporters-subpoena-leaks', 'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/7836x4408+0+408/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fab%2Fde%2F481878534d12b386c554f6a1a745%2Fgettyimages-2206692415.jpg', 'publishedAt': '2025-04-26T00:26:39Z', 'content': 'The Justice Department on Friday rescinded a Biden-era policy that provided protections to journalists in leak investigations, paving the way for authorities to once again use subpoenas and compel te… [+2469 chars]'}, {'source': {'id': None, 'name': 'Variety'}, 'author': 'Lauren Coates', 'title': "'You' Series Finale: How Joe Goldberg Goes to Prison, Marienne's Return - Variety", 'description': "'You' finale: showrunners Justin Lo and Michael Foley break down the Season 5 series ending—where Joe Goldberg ends up, Penn Badgley's influence, Cardi B.", 'url': 'https://variety.com/2025/tv/news/you-series-finale-joe-goldberg-prison-marienne-return-1236378345/', 'urlToImage': 'https://variety.com/wp-content/uploads/2025/04/Penn-Badgley-Joe-Goldberg-You-S5.png?crop=0px%2C3px%2C1000px%2C562px&resize=1000%2C563', 'publishedAt': '2025-04-25T23:30:00Z', 'content': 'SPOILER ALERT:\xa0This story contains spoilers for the series finale of “You,” now streaming on Netflix.\r\nJoe Goldberg is finally in a cage for good, and not the one of his own making. In the series fin… [+11703 chars]'}, {'source': {'id': 'politico', 'name': 'Politico'}, 'author': 'Kyle Cheney, Josh Gerstein', 'title': 'How a Trump administration crackdown on foreign students unraveled - Politico', 'description': 'The administration reversed course after dozens of judges ordered it to reinstate legal records for student visa holders.', 'url': 'https://www.politico.com/news/2025/04/25/foreign-students-visas-donald-trump-00311600', 'urlToImage': 'https://static.politico.com/b3/2a/f1e6788a4d4c91da2f223ddbc078/trump-88965.jpg', 'publishedAt': '2025-04-25T23:10:02Z', 'content': 'The whiplash-inducing turnabout was a fresh setback for the administrations aggressive crackdown on foreign students and for President Donald Trumps broader immigration agenda, which has been mired i… [+13700 chars]'}, {'source': {'id': 'bloomberg', 'name': 'Bloomberg'}, 'author': 'Kara Carlson', 'title': 'Bezos-Backed Startup Launches Cheap, US-Made Electric Pickup - Bloomberg.com', 'description': 'A Jeff Bezos-backed startup aims to appeal to American car buyers’ patriotism and pocketbooks.', 'url': 'https://www.bloomberg.com/news/articles/2025-04-25/bezos-backed-startup-launches-cheap-us-made-electric-pickup', 'urlToImage': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iQ3CHPZgzoLQ/v1/1200x800.jpg', 'publishedAt': '2025-04-25T22:31:48Z', 'content': 'A Jeff Bezos-backed startup aims to appeal to American car buyers patriotism and pocketbooks. \r\nSlate Auto plans to debut a small electric-powered, American-made pickup for less than $20,000 with fed… [+235 chars]'}, {'source': {'id': None, 'name': '9News.com KUSA'}, 'author': 'Wilson Beese (9NEWS)', 'title': '3rd measles case confirmed in Denver area - 9News', 'description': "The Denver County resident who was vaccinated recently returned from Mexico, and officials warned of possible exposures at urgent care at Kaiser's Lakewood office.", 'url': 'https://www.9news.com/article/news/health/measles-case-lakewood-colorado/73-947abde8-a7f3-4a45-802a-69a6efe42911', 'urlToImage': 'https://media.9news.com/assets/KUSA/images/1e3b9f23-6755-4366-92b6-b4e47df9808c/20250401T152943/1e3b9f23-6755-4366-92b6-b4e47df9808c_1140x641.jpg', 'publishedAt': '2025-04-25T22:28:00Z', 'content': 'LAKEWOOD, Colo. Colorado health officials on Friday confirmed a fifth measles case in the state.\r\nThe Colorado Department of Public Health and Environment (CDPHE) said a Denver County resident recent… [+1517 chars]'}, {'source': {'id': None, 'name': 'Gizmodo.com'}, 'author': 'Sabina Graves', 'title': 'DC Studios’ Superman Will Soar Globally After Warner Bros. Legal Win - Gizmodo', 'description': 'Fear not, international fans: the James Gunn-helmed movie will indeed open July 11.', 'url': 'https://gizmodo.com/dc-studios-superman-will-soar-globally-after-warner-bros-legal-win-2000594667', 'urlToImage': 'https://gizmodo.com/app/uploads/2025/04/superman-dc-studios.jpg', 'publishedAt': '2025-04-25T22:01:24Z', 'content': 'A lawsuit brought by the estate of Superman co-creator Joseph Schuster which attempted to block the film’s release in Australia, Canada, Ireland, and the United Kingdomthanks to an old law kink that … [+1618 chars]'}, {'source': {'id': None, 'name': 'Hollywood Reporter'}, 'author': 'Borys Kit', 'title': 'Emma Mackey to Star as the White Witch in Greta Gerwig’s ‘Narnia’ (Exclusive) - The Hollywood Reporter', 'description': "The Netflix adaptation reunites the English actress with her 'Barbie' director.", 'url': 'http://www.hollywoodreporter.com/movies/movie-news/emma-mackey-white-witch-in-greta-gerwig-narnia-1236201064/', 'urlToImage': 'https://www.hollywoodreporter.com/wp-content/uploads/2024/11/GettyImages-1690730740-H-2024.jpg?w=1296&h=730&crop=1', 'publishedAt': '2025-04-25T21:12:19Z', 'content': 'The White Witch has been found.\r\nBritish actress Emma Mackey has nabbed the coveted role of the evil spellcaster in Narnia, Greta Gerwig’s adaptation of C.S. Lewis’ The Chronicles of Narnia fantasy n… [+2172 chars]'}, {'source': {'id': 'ars-technica', 'name': 'Ars Technica'}, 'author': 'John Timmer', 'title': 'New study: There are lots of icy super-Earths - Ars Technica', 'description': '“Microlensing” lets us find planets at much greater distances from their star.', 'url': 'https://arstechnica.com/science/2025/04/new-study-there-are-lots-of-icy-super-earths/', 'urlToImage': 'https://cdn.arstechnica.net/wp-content/uploads/2025/04/image-4-1041x648.jpeg', 'publishedAt': '2025-04-25T21:06:25Z', 'content': None}, {'source': {'id': None, 'name': 'Hollywood Reporter'}, 'author': 'Pamela McClintock', 'title': 'Box Office: ‘Sinners’ Eyes Astounding $30M-$40M, ‘Accountant 2’ Gains Edge Over ‘Revenge of the Sith’ - The Hollywood Reporter', 'description': "In a weekend for the history books, Ben Affleck's 'The Accountant 2' is holding its own as 2005's 'Star Wars: Revenge of the Sith' looks to score one of the top openings ever for a rerelease and 'Sinners' continues to break the bank.", 'url': 'http://www.hollywoodreporter.com/movies/movie-news/star-wars-revenge-sith-box-office-previews-accountant-1236200735/', 'urlToImage': 'https://www.hollywoodreporter.com/wp-content/uploads/2025/04/Star-Wars-Revenge-of-the-Sith-and-The-Accountant-Split-Everett-H-2025.jpg?w=1296&h=730&crop=1', 'publishedAt': '2025-04-25T20:48:45Z', 'content': 'Talk about a blast from the past.\r\nLucasfilm and Disney’s 20th Anniversary rerelease of Star Wars: Episode III – Revenge of the Sith soared to $3.4 million in Thursday previews ahead of its limited o… [+4404 chars]'}, {'source': {'id': 'cnn', 'name': 'CNN'}, 'author': 'Lauren Kent', 'title': 'Cardinals seal Pope Francis’ coffin, formally ending his lying in state at the Vatican - CNN', 'description': 'Pope Francis’ wooden coffin was sealed on Friday night, in a private rite that officially ends three days of his body lying in state at the Vatican.', 'url': 'https://www.cnn.com/2025/04/25/europe/pope-francis-coffin-close-vatican-intl/index.html', 'urlToImage': 'https://media.cnn.com/api/v1/images/stellar/prod/2025-04-25t195802z-2007515856-rc265eavg0ww-rtrmadp-3-pope-francis.jpg?c=16x9&q=w_800,c_fill', 'publishedAt': '2025-04-25T20:42:00Z', 'content': 'Pope Francis wooden coffin was sealed on Friday night, in a private rite that officially ends three days of his body lying in state at the Vatican.\r\nAbout 250,000 people filed through St. Peters Basi… [+3401 chars]'}, {'source': {'id': None, 'name': 'BleepingComputer'}, 'author': 'Lawrence Abrams', 'title': 'Windows 11 KB5055627 update released with 30 new changes, fixes - BleepingComputer', 'description': '\u200b\u200bMicrosoft has released the KB5055627 preview cumulative update for Windows 11 24H2\xa0with many new features gradually rolling out, and some new bug fixes for everyone.', 'url': 'https://www.bleepingcomputer.com/news/microsoft/windows-11-kb5055627-update-released-with-30-new-changes-fixes/', 'urlToImage': 'https://www.bleepstatic.com/content/hl-images/2024/07/18/Windows--11.jpg', 'publishedAt': '2025-04-25T20:18:41Z', 'content': '\u200b\u200bMicrosoft has released the KB5055627 preview cumulative update for Windows 11 24H2\xa0with many new features gradually rolling out, and some new bug fixes for everyone.\r\nThe KB5055627 update is part o… [+11335 chars]'}]}

In [24]:
import requests

# API endpoint and key
API_URL = "https://newsapi.org/v2/top-headlines"
API_KEY = "3805f6bbabcb42b3a0c08a489baf603d"

# Parameters for the API request
params = {
    "country": "us",
    "apiKey": API_KEY
}

# Making the API request
response = requests.get(API_URL, params=params)

# Checking if the request was successful
if response.status_code == 200:
    # Printing the JSON response
    print(response.json())
else:
    print(f"Error: {response.status_code}")

{'status': 'ok', 'totalResults': 35, 'articles': [{'source': {'id': 'the-wall-street-journal', 'name': 'The Wall Street Journal'}, 'author': 'WSJ', 'title': 'The Chinese Satellite Firm Washington Accuses of Helping U.S. Foes - WSJ', 'description': None, 'url': 'https://www.wsj.com/world/china/the-chinese-satellite-firm-washington-accuses-of-helping-u-s-foes-b5e68d2e', 'urlToImage': None, 'publishedAt': '2025-04-26T03:00:00Z', 'content': None}, {'source': {'id': None, 'name': 'Steelers.com'}, 'author': None, 'title': 'How he fits: Kaleb Johnson, RB, Iowa - Steelers.com', 'description': 'Steelers add big, explosive running back to offense', 'url': 'https://www.steelers.com/news/steelers-how-he-fits-kaleb-johnson-rb-iowa', 'urlToImage': 'https://static.clubs.nfl.com/image/upload/t_editorial_landscape_12_desktop/steelers/sitxpggfyp3by8xaqmx4', 'publishedAt': '2025-04-26T02:52:26Z', 'content': None}, {'source': {'id': None, 'name': 'clevelandbrowns.com'}, 'author': None, 'title': 'Browns select RB Quinshon Judkins with the No. 36 pick in the 2025 NFL Draft - Cleveland Browns', 'description': 'Judkins totaled 94 carries for 1,060 rushing yards and 14 touchdowns in 2024 season at OSU', 'url': 'https://www.clevelandbrowns.com/news/browns-select-rb-quinshon-judkins-with-the-no-36-pick-in-the-2025-nfl-draft', 'urlToImage': 'https://static.clubs.nfl.com/image/upload/t_editorial_landscape_12_desktop/browns/jlh8qymtql0coqwctkwf', 'publishedAt': '2025-04-26T02:16:44Z', 'content': None}, {'source': {'id': 'fox-sports', 'name': 'Fox Sports'}, 'author': 'Rob Rang', 'title': '2025 NFL Draft: Shedeur Sanders among best players available on Day 2 - FOX Sports', 'description': "The Shedeur Sanders slide that had been rumored for days has manifested beyond belief. He's now among Rob Rang's best players available heading into Day 3 of the NFL Draft.", 'url': 'https://www.foxsports.com/stories/nfl/2025-nfl-draft-best-players-available', 'urlToImage': 'https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2025/04/1408/814/16x9-2.jpg?ve=1&tl=1', 'publishedAt': '2025-04-26T02:14:00Z', 'content': 'A Shedeur Sanders slide had been rumored for days, but no one knew for certain when the polarizing quarterback would be selected. After Day 2 of the 2025 NFL Draft, that still remains a mystery.\r\nThr… [+15162 chars]'}, {'source': {'id': 'the-washington-post', 'name': 'The Washington Post'}, 'author': 'Mark Berman', 'title': 'Former congressman George Santos sentenced to more than 7 years in prison - The Washington Post', 'description': 'Former U.S. representative George Santos pleaded guilty last year to federal charges of aggravated identity theft and wire fraud.', 'url': 'https://www.washingtonpost.com/politics/2025/04/25/george-santos-sentencing-fraud-case/', 'urlToImage': 'https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/DTFL4R5PIM2EYHJMM5A3SP7ATU_size-normalized.jpg&w=1440', 'publishedAt': '2025-04-26T01:57:47Z', 'content': 'George Santos, the disgraced former congressman who was expelled from the House after being accused of financial misconduct and telling myriad lies about his background, was sentenced Friday to more … [+5086 chars]'}, {'source': {'id': None, 'name': 'BBC News'}, 'author': None, 'title': 'Virginia Giuffre, Prince Andrew and Jeffrey Epstein accuser, dies by suicide - BBC', 'description': 'Giuffre alleged she was trafficked to the Duke of York when she was 17, which he has strenuously denied.', 'url': 'https://www.bbc.com/news/articles/cql67qk0dd3o', 'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/faf7/live/905212e0-223e-11f0-83ed-3374ea04608c.jpg', 'publishedAt': '2025-04-26T01:48:32Z', 'content': 'Christal Hayes\r\nVirginia Giuffre, who accused Prince Andrew and Jeffrey Epstein of sexual abuse, has died by suicide aged 41, her family has confirmed.\r\nGiuffre was one of the most outspoken accusers… [+2885 chars]'}, {'source': {'id': None, 'name': 'Mile High Report'}, 'author': 'Tim Lynch', 'title': 'Snap reactions to the Broncos second round pick, RJ Harvey - Mile High Report', 'description': 'The Denver Broncos maneuvered through the back half of the second round in brilliant fashion and still landed their home run threat at running back.', 'url': 'https://www.milehighreport.com/2025/4/25/24417230/reactions-to-denver-broncos-second-round-pick-of-rj-harvey', 'urlToImage': 'https://cdn.vox-cdn.com/thumbor/xuKuX6HYK8Fht2E_g0dUtuOV0Z8=/0x0:4800x2513/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/25970011/usa_today_24656312.jpg', 'publishedAt': '2025-04-26T01:31:53Z', 'content': 'The Denver Broncos made some excellent moves to trade back twice from the 51st pick to the 60th moving up double-digit spots in both the third and fourth round, while also picking up an additional fo… [+2321 chars]'}, {'source': {'id': None, 'name': 'NPR'}, 'author': '', 'title': 'Justice Department revokes Biden-era protections for reporters in leak investigations - NPR', 'description': 'In a new memo, Attorney General Pam Bondi said the DOJ will allow for subpoenas, court orders and search warrants to get information and testimony from journalists.', 'url': 'https://www.npr.org/2025/04/25/nx-s1-5377624/pam-bondi-reporters-subpoena-leaks', 'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/7836x4408+0+408/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fab%2Fde%2F481878534d12b386c554f6a1a745%2Fgettyimages-2206692415.jpg', 'publishedAt': '2025-04-26T00:26:39Z', 'content': 'The Justice Department on Friday rescinded a Biden-era policy that provided protections to journalists in leak investigations, paving the way for authorities to once again use subpoenas and compel te… [+2469 chars]'}, {'source': {'id': None, 'name': 'Variety'}, 'author': 'Lauren Coates', 'title': "'You' Series Finale: How Joe Goldberg Goes to Prison, Marienne's Return - Variety", 'description': "'You' finale: showrunners Justin Lo and Michael Foley break down the Season 5 series ending—where Joe Goldberg ends up, Penn Badgley's influence, Cardi B.", 'url': 'https://variety.com/2025/tv/news/you-series-finale-joe-goldberg-prison-marienne-return-1236378345/', 'urlToImage': 'https://variety.com/wp-content/uploads/2025/04/Penn-Badgley-Joe-Goldberg-You-S5.png?crop=0px%2C3px%2C1000px%2C562px&resize=1000%2C563', 'publishedAt': '2025-04-25T23:30:00Z', 'content': 'SPOILER ALERT:\xa0This story contains spoilers for the series finale of “You,” now streaming on Netflix.\r\nJoe Goldberg is finally in a cage for good, and not the one of his own making. In the series fin… [+11703 chars]'}, {'source': {'id': 'politico', 'name': 'Politico'}, 'author': 'Kyle Cheney, Josh Gerstein', 'title': 'How a Trump administration crackdown on foreign students unraveled - Politico', 'description': 'The administration reversed course after dozens of judges ordered it to reinstate legal records for student visa holders.', 'url': 'https://www.politico.com/news/2025/04/25/foreign-students-visas-donald-trump-00311600', 'urlToImage': 'https://static.politico.com/b3/2a/f1e6788a4d4c91da2f223ddbc078/trump-88965.jpg', 'publishedAt': '2025-04-25T23:10:02Z', 'content': 'The whiplash-inducing turnabout was a fresh setback for the administrations aggressive crackdown on foreign students and for President Donald Trumps broader immigration agenda, which has been mired i… [+13700 chars]'}, {'source': {'id': 'bloomberg', 'name': 'Bloomberg'}, 'author': 'Kara Carlson', 'title': 'Bezos-Backed Startup Launches Cheap, US-Made Electric Pickup - Bloomberg.com', 'description': 'A Jeff Bezos-backed startup aims to appeal to American car buyers’ patriotism and pocketbooks.', 'url': 'https://www.bloomberg.com/news/articles/2025-04-25/bezos-backed-startup-launches-cheap-us-made-electric-pickup', 'urlToImage': 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iQ3CHPZgzoLQ/v1/1200x800.jpg', 'publishedAt': '2025-04-25T22:31:48Z', 'content': 'A Jeff Bezos-backed startup aims to appeal to American car buyers patriotism and pocketbooks. \r\nSlate Auto plans to debut a small electric-powered, American-made pickup for less than $20,000 with fed… [+235 chars]'}, {'source': {'id': None, 'name': '9News.com KUSA'}, 'author': 'Wilson Beese (9NEWS)', 'title': '3rd measles case confirmed in Denver area - 9News', 'description': "The Denver County resident who was vaccinated recently returned from Mexico, and officials warned of possible exposures at urgent care at Kaiser's Lakewood office.", 'url': 'https://www.9news.com/article/news/health/measles-case-lakewood-colorado/73-947abde8-a7f3-4a45-802a-69a6efe42911', 'urlToImage': 'https://media.9news.com/assets/KUSA/images/1e3b9f23-6755-4366-92b6-b4e47df9808c/20250401T152943/1e3b9f23-6755-4366-92b6-b4e47df9808c_1140x641.jpg', 'publishedAt': '2025-04-25T22:28:00Z', 'content': 'LAKEWOOD, Colo. Colorado health officials on Friday confirmed a fifth measles case in the state.\r\nThe Colorado Department of Public Health and Environment (CDPHE) said a Denver County resident recent… [+1517 chars]'}, {'source': {'id': None, 'name': 'Gizmodo.com'}, 'author': 'Sabina Graves', 'title': 'DC Studios’ Superman Will Soar Globally After Warner Bros. Legal Win - Gizmodo', 'description': 'Fear not, international fans: the James Gunn-helmed movie will indeed open July 11.', 'url': 'https://gizmodo.com/dc-studios-superman-will-soar-globally-after-warner-bros-legal-win-2000594667', 'urlToImage': 'https://gizmodo.com/app/uploads/2025/04/superman-dc-studios.jpg', 'publishedAt': '2025-04-25T22:01:24Z', 'content': 'A lawsuit brought by the estate of Superman co-creator Joseph Schuster which attempted to block the film’s release in Australia, Canada, Ireland, and the United Kingdomthanks to an old law kink that … [+1618 chars]'}, {'source': {'id': None, 'name': 'Hollywood Reporter'}, 'author': 'Borys Kit', 'title': 'Emma Mackey to Star as the White Witch in Greta Gerwig’s ‘Narnia’ (Exclusive) - The Hollywood Reporter', 'description': "The Netflix adaptation reunites the English actress with her 'Barbie' director.", 'url': 'http://www.hollywoodreporter.com/movies/movie-news/emma-mackey-white-witch-in-greta-gerwig-narnia-1236201064/', 'urlToImage': 'https://www.hollywoodreporter.com/wp-content/uploads/2024/11/GettyImages-1690730740-H-2024.jpg?w=1296&h=730&crop=1', 'publishedAt': '2025-04-25T21:12:19Z', 'content': 'The White Witch has been found.\r\nBritish actress Emma Mackey has nabbed the coveted role of the evil spellcaster in Narnia, Greta Gerwig’s adaptation of C.S. Lewis’ The Chronicles of Narnia fantasy n… [+2172 chars]'}, {'source': {'id': 'ars-technica', 'name': 'Ars Technica'}, 'author': 'John Timmer', 'title': 'New study: There are lots of icy super-Earths - Ars Technica', 'description': '“Microlensing” lets us find planets at much greater distances from their star.', 'url': 'https://arstechnica.com/science/2025/04/new-study-there-are-lots-of-icy-super-earths/', 'urlToImage': 'https://cdn.arstechnica.net/wp-content/uploads/2025/04/image-4-1041x648.jpeg', 'publishedAt': '2025-04-25T21:06:25Z', 'content': None}, {'source': {'id': None, 'name': 'Hollywood Reporter'}, 'author': 'Pamela McClintock', 'title': 'Box Office: ‘Sinners’ Eyes Astounding $30M-$40M, ‘Accountant 2’ Gains Edge Over ‘Revenge of the Sith’ - The Hollywood Reporter', 'description': "In a weekend for the history books, Ben Affleck's 'The Accountant 2' is holding its own as 2005's 'Star Wars: Revenge of the Sith' looks to score one of the top openings ever for a rerelease and 'Sinners' continues to break the bank.", 'url': 'http://www.hollywoodreporter.com/movies/movie-news/star-wars-revenge-sith-box-office-previews-accountant-1236200735/', 'urlToImage': 'https://www.hollywoodreporter.com/wp-content/uploads/2025/04/Star-Wars-Revenge-of-the-Sith-and-The-Accountant-Split-Everett-H-2025.jpg?w=1296&h=730&crop=1', 'publishedAt': '2025-04-25T20:48:45Z', 'content': 'Talk about a blast from the past.\r\nLucasfilm and Disney’s 20th Anniversary rerelease of Star Wars: Episode III – Revenge of the Sith soared to $3.4 million in Thursday previews ahead of its limited o… [+4404 chars]'}, {'source': {'id': 'cnn', 'name': 'CNN'}, 'author': 'Lauren Kent', 'title': 'Cardinals seal Pope Francis’ coffin, formally ending his lying in state at the Vatican - CNN', 'description': 'Pope Francis’ wooden coffin was sealed on Friday night, in a private rite that officially ends three days of his body lying in state at the Vatican.', 'url': 'https://www.cnn.com/2025/04/25/europe/pope-francis-coffin-close-vatican-intl/index.html', 'urlToImage': 'https://media.cnn.com/api/v1/images/stellar/prod/2025-04-25t195802z-2007515856-rc265eavg0ww-rtrmadp-3-pope-francis.jpg?c=16x9&q=w_800,c_fill', 'publishedAt': '2025-04-25T20:42:00Z', 'content': 'Pope Francis wooden coffin was sealed on Friday night, in a private rite that officially ends three days of his body lying in state at the Vatican.\r\nAbout 250,000 people filed through St. Peters Basi… [+3401 chars]'}, {'source': {'id': None, 'name': 'BleepingComputer'}, 'author': 'Lawrence Abrams', 'title': 'Windows 11 KB5055627 update released with 30 new changes, fixes - BleepingComputer', 'description': '\u200b\u200bMicrosoft has released the KB5055627 preview cumulative update for Windows 11 24H2\xa0with many new features gradually rolling out, and some new bug fixes for everyone.', 'url': 'https://www.bleepingcomputer.com/news/microsoft/windows-11-kb5055627-update-released-with-30-new-changes-fixes/', 'urlToImage': 'https://www.bleepstatic.com/content/hl-images/2024/07/18/Windows--11.jpg', 'publishedAt': '2025-04-25T20:18:41Z', 'content': '\u200b\u200bMicrosoft has released the KB5055627 preview cumulative update for Windows 11 24H2\xa0with many new features gradually rolling out, and some new bug fixes for everyone.\r\nThe KB5055627 update is part o… [+11335 chars]'}]}

In [27]:
!pip install geocoder

Collecting geocoder
  Downloading geocoder-1.38.1-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: click in c:\users\swaya\anaconda3\lib\site-packages (from geocoder) (8.1.7)
Collecting future (from geocoder)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting ratelim (from geocoder)
  Downloading ratelim-0.1.6-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: requests in c:\users\swaya\anaconda3\lib\site-packages (from geocoder) (2.32.2)
Requirement already satisfied: six in c:\users\swaya\anaconda3\lib\site-packages (from geocoder) (1.16.0)
Requirement already satisfied: colorama in c:\users\swaya\anaconda3\lib\site-packages (from click->geocoder) (0.4.6)
Requirement already satisfied: decorator in c:\users\swaya\anaconda3\lib\site-packages (from ratelim->geocoder) (5.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\swaya\anaconda3\lib\site-packages (from requests->geocoder) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\swaya\anaconda3\lib\site-packages (from requests->geocoder) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\swaya\anaconda3\lib\site-packages (from requests->geocoder) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\swaya\anaconda3\lib\site-packages (from requests->geocoder) (2025.1.31)
Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
   ---------------------------------------- 0.0/98.6 kB ? eta -:--:--
   ---------------------------------------- 98.6/98.6 kB 2.9 MB/s eta 0:00:00
Downloading future-1.0.0-py3-none-any.whl (491 kB)
   ---------------------------------------- 0.0/491.3 kB ? eta -:--:--
   --------------- ------------------------ 184.3/491.3 kB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 419.8/491.3 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 491.3/491.3 kB 3.8 MB/s eta 0:00:00
Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Installing collected packages: ratelim, future, geocoder
Successfully installed future-1.0.0 geocoder-1.38.1 ratelim-0.1.6

In [28]:
import json
import turtle
import urllib.request
import time
import webbrowser
import geocoder

# Get the current ISS data
url = "http://api.open-notify.org/astros.json"
response = urllib.request.urlopen(url)
result = json.loads(response.read())

# Save data to a text file
file = open("iss.txt", "w")
file.write("There are currently " +
            str(result["number"]) + " astronauts on the ISS: \n\n")
people = result["people"]

# Save the crew names to the file
for p in people:
    file.write(p['name'] + " - on board" + "\n")

# Get current latitude and longitude
g = geocoder.ip('me')
file.write("\nYour current lat / long is: " + str(g.latlng))
file.close()

# Open the text file in the browser
webbrowser.open("iss.txt")

# Setup the world map in turtle module
screen = turtle.Screen()
screen.setup(1280, 720)
screen.setworldcoordinates(-180, -90, 180, 90)

# Load the world map image
screen.bgpic("images/map.gif")
screen.register_shape("images/iss.gif")
iss = turtle.Turtle()
iss.shape("images/iss.gif")
iss.setheading(45)
iss.penup()

while True:
    # Get the current ISS position in real-time
    url = "http://api.open-notify.org/iss-now.json"
    response = urllib.request.urlopen(url)
    result = json.loads(response.read())

    # Extract the ISS location
    location = result["iss_position"]
    lat = location['latitude']
    lon = location['longitude']

    # Output lon and lat to the terminal
    lat = float(lat)
    lon = float(lon)
    print("\nLatitude: " + str(lat))
    print("\nLongitude: " + str(lon))

    # Update the ISS location on the map
    iss.goto(lon, lat)

    # Refresh every 5 seconds
    time.sleep(5)

TclError: couldn't open "images/map.gif": no such file or directory

In [1]:
#Example3
#fetching Air Pollution Data through the API provided by the Indian government on data.gov.in

In [9]:
urlData = requests.get("https://api.data.gov.in/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b&format=csv&offset=0&limit=2000").content
#Converting the data to pandas dataframe.
rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')))
rawData.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",27-04-2025 10:00:00,16.509717,80.612222,NO2,28.0,45.0,37.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",27-04-2025 10:00:00,16.509717,80.612222,CO,27.0,31.0,28.0
2,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",27-04-2025 10:00:00,16.554731,80.649110,NH3,4.0,5.0,4.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",27-04-2025 10:00:00,17.720000,83.300000,PM2.5,26.0,47.0,36.0
4,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",27-04-2025 10:00:00,17.720000,83.300000,PM10,50.0,127.0,74.0

In [6]:
import requests

In [8]:
import io
import pandas as pd

In [10]:
rawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        10 non-null     object
 1   state          10 non-null     object
 2   city           10 non-null     object
 3   station        10 non-null     object
 4   last_update    10 non-null     object
 5   latitude       10 non-null     float64
 6   longitude      10 non-null     float64
 7   pollutant_id   10 non-null     object
 8   pollutant_min  8 non-null      float64
 9   pollutant_max  8 non-null      float64
 10  pollutant_avg  8 non-null      float64
dtypes: float64(5), object(6)
memory usage: 1012.0+ bytes

In [11]:
rawData

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",27-04-2025 10:00:00,16.509717,80.612222,NO2,28.0,45.0,37.0
1,India,Andhra_Pradesh,Vijayawada,"Rajiv Gandhi Park, Vijayawada - APPCB",27-04-2025 10:00:00,16.509717,80.612222,CO,27.0,31.0,28.0
2,India,Andhra_Pradesh,Vijayawada,"Rajiv Nagar, Vijayawada - APPCB",27-04-2025 10:00:00,16.554731,80.649110,NH3,4.0,5.0,4.0
3,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",27-04-2025 10:00:00,17.720000,83.300000,PM2.5,26.0,47.0,36.0
4,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",27-04-2025 10:00:00,17.720000,83.300000,PM10,50.0,127.0,74.0
5,India,Andhra_Pradesh,Visakhapatnam,"GVM Corporation, Visakhapatnam - APPCB",27-04-2025 10:00:00,17.720000,83.300000,CO,8.0,72.0,16.0
6,India,Assam,Byrnihat,"Central Academy for SFS, Byrnihat - PCBA",27-04-2025 10:00:00,26.071318,91.874880,PM10,NaN,NaN,NaN
7,India,Bihar,Gaya,"SFTI Kusdihra, Gaya - BSPCB",27-04-2025 10:00:00,24.762518,84.982348,NH3,3.0,4.0,3.0
8,India,Bihar,Katihar,"Mirchaibari, Katihar - BSPCB",27-04-2025 10:00:00,25.560083,87.553265,PM10,NaN,NaN,NaN
9,India,Bihar,Katihar,"Mirchaibari, Katihar - BSPCB",27-04-2025 10:00:00,25.560083,87.553265,NO2,4.0,16.0,14.0