# Selenium
Selenium is a popular Python module used for automating web browsers. It allows developers to control web browsers programmatically, enabling tasks such as web scraping, automated testing, and web application interaction. Selenium supports various web browsers, including Chrome, Firefox, Safari, and Edge, making it a versatile tool for browser automation.

## For Chrome
We import the webdriver module from the Selenium library.
We specify the path to the web driver executable. You need to download the appropriate driver for your browser and provide the path to it. In this example, we’re using the Chrome driver.
We create a new instance of the web browser using webdriver.Chrome() and pass the path to the Chrome driver executable as an argument.
We navigate to a webpage by calling the get() method on the browser object and passing the URL of the webpage.
We extract information from the webpage using various methods provided by Selenium. In this example, we retrieve the page title using the title attribute of the browser object.
Finally, we close the browser using the quit() method.

In [6]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

In [5]:
pip install selenium

Requirement already satisfied: selenium in c:\users\swaya\anaconda3\lib\site-packages (4.31.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\swaya\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.26.20)
Requirement already satisfied: trio~=0.17 in c:\users\swaya\anaconda3\lib\site-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\swaya\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\swaya\anaconda3\lib\site-packages (from selenium) (2025.1.31)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\swaya\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\swaya\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\swaya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\swaya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\swaya\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\swaya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\swaya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
# importing necessary packages
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

# for holding the resultant list
element_list = []
service=Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

for page in range(1, 3, 1):

    page_url = "https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page={}".format(str(page))
    driver.get(page_url)
    title = driver.find_elements(By.CLASS_NAME, "title")
    price = driver.find_elements(By.CLASS_NAME, "price")
    description = driver.find_elements(By.CLASS_NAME, "description")
    rating = driver.find_elements(By.CLASS_NAME, "ratings")

    for i in range(len(title)):
        element_list.append([title[i].text, price[i].text, description[i].text, rating[i].text])

print(element_list)

#closing the driver
driver.close()

[['Packard 255 G2', '$416.99', '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1', '2 reviews'], ['Aspire E1-510', '$306.99', '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux', '2 reviews'], ['ThinkPad T540p', '$1178.99', '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit', '2 reviews'], ['ProBook', '$739.99', '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit', '8 reviews'], ['ThinkPad X240', '$1311.99', '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit', '12 reviews'], ['Aspire E1-572G', '$581.99', '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1', '2 reviews'], ['ThinkPad Yoga', '$1033.99', '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,', '13 reviews'], ['Pavilion', '$609.99', '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1', '4 reviews'], ['Inspiron 15', '$745.99', 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,', '12 reviews'], ['Dell XPS 13', '$1281.99', '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1', '4 reviews'], ['ThinkPad X230', '$1244.99', '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit', '10 reviews'], ['HP 250 G3', '$520.99', '15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1', '13 reviews']]

In [22]:
import pandas as pd
df=pd.DataFrame(element_list,columns=["Laptop_Model","Price","Features","Reviews"])

In [23]:
df

      Laptop_Model     Price                                           Features     Reviews
0   Packard 255 G2   $416.99  15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...   2 reviews
1    Aspire E1-510   $306.99    15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux   2 reviews
2   ThinkPad T540p  $1178.99   15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit   2 reviews
3          ProBook   $739.99    14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit   8 reviews
4    ThinkPad X240  $1311.99  12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...  12 reviews
5   Aspire E1-572G   $581.99  15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...   2 reviews
6    ThinkPad Yoga  $1033.99  12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...  13 reviews
7         Pavilion   $609.99      15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1   4 reviews
8      Inspiron 15   $745.99  Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, R...  12 reviews
9      Dell XPS 13  $1281.99  13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...   4 reviews
10   ThinkPad X230  $1244.99  12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...  10 reviews
11       HP 250 G3   $520.99      15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1  13 reviews

In [27]:
df['Reviews']=df['Reviews'].str.extract('(\d)').astype(int)

      Laptop_Model     Price                                           Features  Reviews
0   Packard 255 G2   $416.99  15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...        2
1    Aspire E1-510   $306.99    15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux        2
2   ThinkPad T540p  $1178.99   15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit        2
3          ProBook   $739.99    14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit        8
4    ThinkPad X240  $1311.99  12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...       12
5   Aspire E1-572G   $581.99  15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...        2
6    ThinkPad Yoga  $1033.99  12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...       13
7         Pavilion   $609.99      15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1        4
8      Inspiron 15   $745.99  Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, R...       12
9      Dell XPS 13  $1281.99  13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...        4
10   ThinkPad X230  $1244.99  12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...       10
11       HP 250 G3   $520.99      15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1       13

In [28]:
df['Features'] = df['Features'].str.split(',\s*')

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\swaya\AppData\Local\Temp\ipykernel_2856\3343794552.py:1: SyntaxWarning: invalid escape sequence '\s'
  df['Features'] = df['Features'].str.split(',\s*')

In [29]:
df

      Laptop_Model     Price                                           Features  Reviews
0   Packard 255 G2   $416.99  [15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Window...        2
1    Aspire E1-510   $306.99  [15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux]        2
2   ThinkPad T540p  $1178.99  [15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64...        2
3          ProBook   $739.99  [14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit]        8
4    ThinkPad X240  $1311.99  [12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pr...       12
5   Aspire E1-572G   $581.99  [15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M26...        2
6    ThinkPad Yoga  $1033.99  [12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB...       13
7         Pavilion   $609.99    [15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1]        4
8      Inspiron 15   $745.99  [Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, ...       12
9      Dell XPS 13  $1281.99  [13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, W...        4
10   ThinkPad X230  $1244.99  [12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 P...       10
11       HP 250 G3   $520.99    [15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1]       13

In [31]:
features_df=pd.DataFrame(df['Features'].to_list())

In [35]:
features_df.columns=['Screen_size',"Processor",'Ram',"Rom","OS",'R1','R2']

In [36]:
features_df

    Screen_size              Processor            Ram  ...              OS                     R1    R2
0         15.6"     AMD E2-3800 1.3GHz            4GB  ...     Windows 8.1                   None  None
1         15.6"  Pentium N3520 2.16GHz            4GB  ...           Linux                   None  None
2         15.6"          Core i5-4200M            4GB  ...  Win7 Pro 64bit                   None  None
3           14"         Core i5 2.6GHz            4GB  ...  Win7 Pro 64bit                   None  None
4         12.5"          Core i5-4300U            8GB  ...  Win7 Pro 64bit                   None  None
5         15.6"          Core i5-4200U            8GB  ...  Radeon R7 M265            Windows 8.1  None
6   12.5" Touch          Core i3-4010U            4GB  ...                                   None  None
7         15.6"          Core i5-4200U            6GB  ...     Windows 8.1                   None  None
8   Moon Silver                  15.6"  Core i7-4510U  ...             1TB  Radeon HD R7 M265 2GB
9   13.3" Touch          Core i5-4210U            8GB  ...     Windows 8.1                   None  None
10        12.5"         Core i5 2.6GHz            8GB  ...  Win7 Pro 64bit                   None  None
11        15.6"          Core i5-4210U            4GB  ...     Windows 8.1                   None  None

[12 rows x 7 columns]