In [2]:
import pandas as pd
import numpy as np

In [3]:
data=np.random.randint(1,100,[6,4])
df=pd.DataFrame(data,columns=['A','B','C','D'])

In [5]:
df.set_index('A',inplace=True)

In [13]:
data=np.random.randint(1,100,[3,3])
df=pd.DataFrame(data,columns=['A','B','C'],index=['X','Y','Z'])

In [14]:
df

    A   B   C
X  12  89  44
Y  21  72  11
Z  53  47   6

In [18]:
df.at['Y','B']

72

In [22]:
df=pd.DataFrame(np.random.randint(1,100,[5,3]),columns=['A','B','C'])

In [24]:
df['Product_A_B']=df['A']*df['B']

In [25]:
df

    A   B   C  Product_A_B
0  31  67  48         2077
1  13  97  76         1261
2  77  98  37         7546
3  19  86  59         1634
4  39  59  97         2301

In [26]:
df=pd.DataFrame(np.random.randint(1,100,[4,3]))

In [27]:
df.sum(axis=1)

0    176
1    104
2     79
3    113
dtype: int64

In [28]:
df.sum(axis=0)

0    180
1    193
2     99
dtype: int64

In [30]:
#Data cleaning
df=pd.DataFrame(np.random.randint(1,100,[5,3]))
df.iloc[0,1]=np.nan
df.iloc[1,2]=np.nan

In [31]:
df

    0     1     2
0  77   NaN  32.0
1  30  35.0   NaN
2  38  24.0  79.0
3  95  93.0  81.0
4  63  33.0  10.0

In [32]:
mean_df=df.mean()

In [33]:
df.fillna(mean_df)

    0      1     2
0  77  46.25  32.0
1  30  35.00  50.5
2  38  24.00  79.0
3  95  93.00  81.0
4  63  33.00  10.0

In [35]:
df=pd.DataFrame(np.random.randint(1,100,[6,4]))
df.iloc[5,3]=np.nan
df.iloc[4,2]=np.nan

In [36]:
df

    0   1     2     3
0   5  67  82.0  35.0
1  99  97  73.0  72.0
2  91  97  85.0  10.0
3  73  69  70.0  65.0
4  55  63   NaN  86.0
5  76  54  49.0   NaN

In [37]:
df.dropna(inplace=True)#dropping null rows

In [38]:
df

    0   1     2     3
0   5  67  82.0  35.0
1  99  97  73.0  72.0
2  91  97  85.0  10.0
3  73  69  70.0  65.0

In [39]:
data={'Category':np.random.choice(['A','B','C'],size=10),'Value':np.random.randint(1,100,size=10)}

In [44]:
df=pd.DataFrame(data)

In [45]:
df.groupby('Category')['Value'].agg(['sum','mean'])

          sum       mean
Category
A         151  50.333333
B         242  80.666667
C         266  66.500000

In [46]:
books=[1001,1002,1003,1004,1005,1006,1007,1008,1009]
overdue={1002,1006}
def display_sorted(book_id,overdue_id):
    found=False

In [47]:
display_sorted(books,overdue)

In [48]:
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

Original DataFrame:
  Product Category  Sales
0   Prod2        C     24
1   Prod2        C     93
2   Prod3        C     80
3   Prod3        B     52
4   Prod3        C     61
5   Prod2        B     54
6   Prod2        A     68
7   Prod3        B     46
8   Prod2        C     58
9   Prod2        A     61

In [51]:
df.groupby('Category')['Sales'].agg('sum')

Category
A    129
B    152
C    316
Name: Sales, dtype: int32

In [ ]:
df1=pd.DataFrame()